export default Images = {
  petOwner: require('../assets/owner.png'),
  cat: require('../assets/cat.png'),
  dog: require('../assets/dog.png'),
  bird: require('../assets/bird.png'),
  rabbit: require('../assets/rabbit.png'),
  turtle: require('../assets/turtle.png'),
  avatar: require('../assets/avatar.jpeg'),
  logo: require('../assets/logo.png'),
  mall: require('../assets/mall.png'),
  doc: require('../assets/doc.png'),
  acc1: require('../assets/acc1.jpeg'),
  acc2: require('../assets/acc2.jpeg'),
  acc3: require('../assets/acc3.jpg'),
  acc4: require('../assets/acc4.jpeg'),
};
