export default Images = {
  petOwner: require('../assets/owner.png'),
  cat: require('../assets/cat.png'),
  dog: require('../assets/dog.png'),
  bird: require('../assets/bird.png'),
  rabbit: require('../assets/rabbit.png'),
  turtle: require('../assets/turtle.png'),
  avatar: require('../assets/avatar.jpeg'),
  logo: require('../assets/logo.png'),
  mall: require('../assets/mall.png'),
  doc: require('../assets/doc.png'),
  acc1: require('../assets/acc1.jpeg'),
  acc2: require('../assets/acc2.jpeg'),
  acc3: require('../assets/acc3.jpg'),
  acc4: require('../assets/acc4.jpeg'),
  DogBack: require('../assets/DogBack.jpeg'),
  clinicImage: require('../assets/clinicImage.png'),
  sell1: require('../assets/sell1.png'),
  sell2: require('../assets/sell2.png'),
  sell3: require('../assets/sell3.png'),
  imagePlaceholder: require('../assets/image-placeholder.jpeg'),
  loginDog: require('../assets/loginDog.png'),
  petTube: require('../assets/petTube.png'),
  sugnupback: require('../assets/sugnupback.jpeg'),
};
